GachaWebApp/Models/ErrorViewModel.cs
using System;

namespace GachaWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GachaWebApp/Models/GachaModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace GachaWebApp.Models
{
    public class GachaModel
    {
        [DisplayName("RARE1排出確率")]
        public float rate1 { get; set; }
        [DisplayName("RARE2排出確率")]
        public float rate2 { get; set; }
        [DisplayName("RARE3排出確率")]
        public float rate3 { get; set; }
        [DisplayName("RARE4排出確率")]
        public float rate4 { get; set; }
        [DisplayName("RARE5排出確率")]
        public float rate5 { get; set; }

        [DisplayName("RARE1カード種類")]
        public int num1 { get; set; }
        [DisplayName("RARE2カード種類")]
        public int num2 { get; set; }
        [DisplayName("RARE3カード種類")]
        public int num3 { get; set; }
        [DisplayName("RARE4カード種類")]
        public int num4 { get; set; }
        [DisplayName("RARE5カード種類")]
        public int num5 { get; set; }

        [DisplayName("ガチャ実行結果回数")]
        [DefaultValue(0)]
        public int playCount { get; set; }

        [DisplayName("ガチャ試行回数")]
        [DefaultValue(0)]
        public int tryCount { get; set; }

        public Dictionary<string, int> result { get; set; }

        public GachaModel()
        {
            tryCount = 100;

            rate1 = 0.40f;
            rate2 = 0.20f;
            rate3 = 0.19f;
            rate4 = 0.18f;
            rate5 = 0.03f;

            num1 = 150;
            num2 = 130;
            num3 = 127;
            num4 = 84;
            num5 = 87;
        }
    }
}

GachaWebApp/Controllers/GachaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GachaWebApp.Models;

namespace GachaWebApp.Controllers
{
    public class GachaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult PlayOnce()
        {
            return View(new GachaModel());
        }
        
        /*
        [HttpPost]
        public IActionResult PlayOnce(GachaModel gachaModel)
        {
            return RedirectToAction("PlayOnceResult", gachaModel);
        }
        */

        Dictionary<int, Conf> confDict;
        int tryCount = 0;

        [HttpPost]
        public IActionResult PlayOnce(GachaModel gachaModel)
        {
            confDict = new Dictionary<int, Conf>();
            confDict.Add(5, new Conf(gachaModel.rate5, gachaModel.num5));
            confDict.Add(4, new Conf(gachaModel.rate4, gachaModel.num4));
            confDict.Add(3, new Conf(gachaModel.rate3, gachaModel.num3));
            confDict.Add(2, new Conf(gachaModel.rate2, gachaModel.num2));
            confDict.Add(1, new Conf(gachaModel.rate1, gachaModel.num1));
            tryCount = gachaModel.tryCount;

            Dictionary<string, int> result;
            gachaModel.playCount = PlayGacha(out result);
            gachaModel.result = result;


            return View("PlayOnceResult", gachaModel);
        }

        class Conf
        {
            public Conf(float _rate, int _num)
            {
                rate = _rate;
                num = _num;
            }
            public float rate;
            public int num;
        }

        int PlayGacha(out Dictionary<string,int> result)
        {
            //コンプすべき全種類数
            int totalNum = confDict.Sum(e => e.Value.num);

            Random rnd = new Random();
            double rndNumRarerity;
            int rndNumSameRarerity;

            Dictionary<string, int> resultDict = new Dictionary<string, int>();

            int totalGet = 0;   //獲得した種別
            int loop = 0;

            bool loopFlg = true;

            do
            {
                rndNumRarerity = rnd.NextDouble();

                int rarelity = 0;
                if (rndNumRarerity <= confDict[5].rate)
                {
                    rarelity = 5;
                }
                else if (rndNumRarerity <= confDict[5].rate + confDict[4].rate)
                {
                    rarelity = 4;
                }
                else if (rndNumRarerity <= confDict[5].rate + confDict[4].rate + confDict[3].rate)
                {
                    rarelity = 3;
                }
                else if (rndNumRarerity <= confDict[5].rate + confDict[4].rate + confDict[3].rate + confDict[2].rate)
                {
                    rarelity = 2;
                }
                else
                {
                    rarelity = 1;
                }

                string id = "";
                if (confDict[rarelity].num > 0)
                {
                    //同一レアリティ内での抽選
                    rndNumSameRarerity = rnd.Next(0, confDict[rarelity].num) + 1;

                    id = rarelity.ToString() + "_" + rndNumSameRarerity.ToString("000");


                }
                else
                {
                    id = rarelity.ToString() + "_対象カードなし";
                }

                if (resultDict.ContainsKey(id))
                {
                    resultDict[id] += 1;
                }
                else
                {
                    resultDict.Add(id, 1);
                }

                loop++;

                totalGet = resultDict.Count;

                if (tryCount > 0)   //試行回数が1以上を指定された
                {
                    if (tryCount <= loop)   //試行回数を達成した
                    {
                        loopFlg = false;
                    }
                }
                else //試行回数0（コンプモード）
                {
                    if (totalGet >= totalNum)   //カードの種類が設定のトータル枚数になった（コンプ）
                    {
                        loopFlg = false;
                    }
                }

            } while (loopFlg);

            var orderDict = resultDict.OrderByDescending(e => e.Key);

            /*
            foreach (KeyValuePair<string, int> p in orderDict)
            {
                System.Diagnostics.Debug.WriteLine(p.Key + ":" + p.Value.ToString());
            }
            */

            //System.Diagnostics.Debug.WriteLine(loop);

            Dictionary<string, int> temp = new Dictionary<string, int>();
            foreach (var p in orderDict)
            {
                temp.Add(p.Key, p.Value);
            };

            result = temp;
            return loop;
        }
    }
}

GachaWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GachaWebApp.Models;

namespace GachaWebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GachaWebApp/Views/Gacha/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<a asp-action="PlayOnce">ガチャ回数指定シミュレーション</a>

GachaWebApp/Views/Gacha/PlayOnce.cshtml
@model GachaWebApp.Models.GachaModel

@{
    ViewData["Title"] = "PlayOnce";
}

<h2>ガチャ回数指定シミュレーション</h2>

<h4>指定された回数ガチャを引き、排出結果を表示します</h4>
<hr />

<div class="row">
    <div class="col-md-8">
        <form asp-action="PlayOnce">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">

                <div class="col-md-4">
                    ガチャ試行回数
                    <div class="text-warning">0を入力すると全種類をコンプするまで引きます</div>
                </div>


                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="tryCount" class="control-label"></label>
                        <input asp-for="tryCount" class="form-control" />
                        <span asp-validation-for="tryCount" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="rate1" class="control-label"></label>
                        <input asp-for="rate1" class="form-control" />
                        <span asp-validation-for="rate1" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="num1" class="control-label"></label>
                        <input asp-for="num1" class="form-control" />
                        <span asp-validation-for="num1" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="rate2" class="control-label"></label>
                        <input asp-for="rate2" class="form-control" />
                        <span asp-validation-for="rate2" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="num2" class="control-label"></label>
                        <input asp-for="num2" class="form-control" />
                        <span asp-validation-for="num2" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="rate3" class="control-label"></label>
                        <input asp-for="rate3" class="form-control" />
                        <span asp-validation-for="rate3" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="num3" class="control-label"></label>
                        <input asp-for="num3" class="form-control" />
                        <span asp-validation-for="num3" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="rate4" class="control-label"></label>
                        <input asp-for="rate4" class="form-control" />
                        <span asp-validation-for="rate4" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="num4" class="control-label"></label>
                        <input asp-for="num4" class="form-control" />
                        <span asp-validation-for="num4" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="rate5" class="control-label"></label>
                        <input asp-for="rate5" class="form-control" />
                        <span asp-validation-for="rate5" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="num5" class="control-label"></label>
                        <input asp-for="num5" class="form-control" />
                        <span asp-validation-for="num5" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <input type="submit" value="実行" class="btn btn-default" />
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Back to Top</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GachaWebApp/Views/Gacha/PlayOnceResult.cshtml
@model GachaWebApp.Models.GachaModel

@{
    ViewData["Title"] = "PlayOnceResult";
}

<h2>PlayOnceResult</h2>

<div>
    <h4>GachaModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            排出確率合計
        </dt>
        <dd>
            @{ 
                var sum = Model.rate1 + Model.rate2 + Model.rate3 + Model.rate4 + Model.rate5;
            }
            @sum
            @if(sum != 1)
            {
            <span>合計が1ではないため不正確な結果となります</span>
            }
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.rate1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.rate1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.rate2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.rate2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.rate3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.rate3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.rate4)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.rate4)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.rate5)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.rate5)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.num1)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.num1)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.num2)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.num2)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.num3)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.num3)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.num4)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.num4)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.num5)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.num5)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.playCount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.playCount)
        </dd>
        <dt>排出結果</dt>
        <dd>
            @foreach (var item in Model.result)
            {
                @if (item.Key.StartsWith("5"))
                {
                    <span class="text-danger" style="padding-right:5px;">レア度@(item.Key),@(item.Value)</span><br />
                }
                else if (item.Key.StartsWith("4"))
                {
                    <span class="text-info" style="padding-right:5px;">レア度@(item.Key),@(item.Value)</span><br />
                }
                else
                {
                    <span class="text-normal" style="padding-right:5px;">レア度@(item.Key),@(item.Value)</span><br />
                }
            }
        </dd>
    </dl>
</div>
<div>
    <a href="#" onclick="window.history.back(); return false;">戻る</a> | 
    <a asp-action="Index">Back to Top</a>
</div>

GachaWebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

GachaWebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GachaWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

GachaWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GachaWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Gacha" asp-action="Index" class="navbar-brand">GachaWebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Gacha" asp-action="Index">Home</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - GachaWebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>